name: Deploy to WordPress.org SVN

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy:
    name: New Version Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: WordPress.org Plugin Deploy
        # We use the full repository path and a verified version
        uses: 10up/action-wordpress-dot-org-deploy@4b00f7e4362a26c4839843a8536b694b8e018659 # Pinning to a specific commit for maximum reliability
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: quantwp-sidecart-for-woocommerce