name: Deploy to WordPress.org SVN

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*' # Triggers whenever you push a version tag (e.g., 3.0.7)

jobs:
  tag:
    name: New Version Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: WordPress.org Plugin Deploy
        uses: 10up/action-wordpress-dot-org-deploy@v2.2.2
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: quantwp-sidecart-for-woocommerce # Your official WordPress.org URL slug
